# Generated by Django 5.2.5 on 2025-08-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('about', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateField(auto_now=True),
        ),
    ]
